### ISSUE TITLE
failed to load pcd file 

### ISSUE THREAD

**Issue by ajay1606** [lgsvl/autoware-data#1]
Hello All,
Thanks for the simulator package its very useful one. I am using autoware quite a long time and recently started use lgsvl simulator with autoware.

I have followed the steps provided in here https://github.com/lgsvl/Autoware. Separately, Simulator and Autoware running successfully. But i am unable to test the autoware along with the simulator because of the pcd loading failed error.

The pcd files provided in the link https://github.com/lgsvl/autoware-data, 
But when i load pcd files (autoware-data-master/data/map/pointcloud_map_sf_portion/) I am getting error, "failed /home/autoware/.autoware/data/map/pointcloud_map_sf_portion/DuckieSimulator_SF_Environment_00000.pcd"

COuld anyone please help me to fix this issue. Thanks in advance.

**Comment by luqiang21** [comment]
@ajay1606 Are you using the launch file in this folder: `~/shared_dir/autoware-data/my_launch_sf_map/`?
It should point to `$(env HOME)/shared_dir/autoware-data/data/map/pointcloud_map_sf_portion/DuckieSimulator_SF_Environment_00000.pcd`. You can follow instructions here: https://github.com/lgsvl/Autoware.

**Comment by ajay1606** [comment]
@luqiang21 Thank you for your response.
Yes, I am sure about the ~/shared_dir/autoware-data/my_launch_sf_map file targetinng the correctly point cloud files in the $(env HOME)/shared_dir/autoware-data/data/map/pointcloud_map_sf_portion/DuckieSimulator_SF_Environment_00000.pcd. 

But i wonder, why there is no any data inside the file **"DuckieSimulator_SF_Environment_00000.pcd"**

When i open the file DuckieSimulator_SF_Environment_00000.pcd, i can see only 
version https://git-lfs.github.com/spec/v1
oid sha256:61bb75e970a7061cf88abac8a621b45197d7871f38fc9ff4708fdea2836b33e1
size 8000141

Could you please comment on this?

regards,
Ajay

**Comment by luqiang21** [comment]
@ajay1606 It looks like you didn't install Git LFS, can you try everything after you install git LFS? Instructions [here](https://git-lfs.github.com/)

**Comment by ajay1606** [comment]
@luqiang21 Thank you so much, I will try and get back to you .

**Comment by ajay1606** [comment]
Thank you so much, now point cloud file is loading in the Autoware.
I really appreciate your help
