### ISSUE TITLE
unable to run the autoware localization with simulator data

### ISSUE THREAD

**Issue by ajay1606** [lgsvl/autoware-data#2]
Hello everyone,

Could anyone please guide me, how to test autoware localization with lgsvl simulator. 
Currently, I have followed all  the steps mentioned in the link https://github.com/lgsvl/Autoware and 
Until launch Rviz - the vector map and point cloud map display everything working fine. But next, i am unable to visualize the simulated LiDAR data from the simulator.
Could anyone please help me, how to connect real-time simulated lidar data with the autoware localization node.

Running Simulator:
![selection_059](https://user-images.githubusercontent.com/29722843/53078928-9eca2780-3538-11e9-986c-a2ab9d720118.png)

Running Autoware:
![selection_060](https://user-images.githubusercontent.com/29722843/53078950-ae497080-3538-11e9-89c3-24d669c61559.png)

After launching rviz:
![selection_062](https://user-images.githubusercontent.com/29722843/53078897-8b1ec100-3538-11e9-95b8-59df2c6277fb.png)

Even though I have clicked "2D Nav Goal" in Rviz, then click a destination point and drag slightly in a feasible direction, i am unable to see any changes in rviz.

Regards,
Ajay

**Comment by hadiTab** [comment]
@ajay1606 Is rosbridge connected? If so, it should say connected at the top of the simulator screen on the left. The my_sensing_simulator.launch file should also launch rosbrige. When you launch it make sure there are no errors in the terminal.

If rosbridge is up, you can also check the rosbridge by trying to read data from the sensors you have activated in the simulator. For example, you can activate the lidar you can echo them and see if you are getting any data:

`rostopic echo /points_raw`

Let me know if this outputs any lidar data. Thanks.

**Comment by ajay1606** [comment]
@hadiTab Than you for your quick response.

Yes I checked as you mentioned in your comment.

**1. Confirmed ROS bridge connected:
![selection_065](https://user-images.githubusercontent.com/29722843/53139535-42fdae00-35cd-11e9-8738-57eabd9be15f.png)
**
2. Sensor data activated (rostopic echo /points_raw) confirmed:
![selection_066](https://user-images.githubusercontent.com/29722843/53139559-5446ba80-35cd-11e9-8ad0-934c1052c6fa.png)

**3. Error Messages in the terminal**
![selection_067](https://user-images.githubusercontent.com/29722843/53139607-7e987800-35cd-11e9-9b60-ff1f5e440da7.png)

4. Error messages in another terminal
![selection_068](https://user-images.githubusercontent.com/29722843/53152307-8a4d6400-35f8-11e9-9993-12e916fb735c.png)


Hope this will helps to fix my issues. Thanks in advance. Looking forward to hearing from you.

Regards,
Ajay

**Comment by hadiTab** [comment]
@ajay1606 are you able to visualize the data in rviz? on the left panel, enable "points_raw" and see if you can find it anywhere. Also if you enable the tf frames you might be able to find the car (look for the velodyne or base_link frames). You can zero in on a frame by selecting it as the "Target frame" in the right panel in rviz and clicking on the "zero" button.

If you are able to find the base_link or velodyne frame somewhere off the map, it probably means that localization is not estimating the correct position for some reason.

Have you changed the content of any of the launch files?

**Comment by ajay1606** [comment]
@hadiTab Thank you so much for your help :) Now its working well.
reason for the error was : roslaunch rosbridge_server rosbridge_websocket.launch..
Because already it was included in **my_sensing_simulator.launch** , so no need to run it again.

**Comment by ntutangyun** [comment]
Hi, I'm actually experiencing another issue shown above.

According to the docs, after I clicked the "Localization" in Autoware's GUI, there should be a time display shown on the right. 

But It's not showing up in my case, same as the screen shot shown in above question. 

Is this normal or did I miss something ?

Thank You

**Comment by AIasd** [comment]
@ntutangyun have you figured it out? I encountered the same issue.
