### ISSUE TITLE
LiDAR - Camera Calibration Data

### ISSUE THREAD

**Issue by hjr1015** [lgsvl/autoware-data#3]
Is calibration file the correct file?

in calibration file, I saw the Image Size. it was [640, 480].

but, lg simulator image size is FHD.

if i use this calibration file on the Autoware, then not working.

so, i changed the simulator image size from FHD to [640, 480].

then, algorithm is working, but lidar-camera data is not matched.

![image](https://user-images.githubusercontent.com/48270292/57495552-b334e980-7309-11e9-8517-301aad764fb4.png)

could I get a correct calibration file?

**Comment by daviduhm** [comment]
We've just updated and pushed a new [camera calibration](https://github.com/lgsvl/autoware-data/blob/master/data/calibration/camera_lidar_3d/prius/camera_lidar_sim_sf.yaml) for both intrinsics and extrinsics. Please pull this latest repo again and restart Autoware detection module as Autoware loads this calibration file in my_detection.launch. 

Below is a screenshot of Lidar point clouds projected onto a camera image correctly with the updated calibration file:
![lidar projection to image](https://user-images.githubusercontent.com/7874480/57546445-9a303680-7311-11e9-9990-ddc2637a9cc0.png)

Sorry about the confusion and please let me know if you still have any issues.
